# One CLI to format the code tree - https://github.com/numtide/treefmt

# Exclude files or directories matching the specified globs
excludes = [
    "LICENSE",
    "*.png",
    "*.jpg",
    "*.md",
    "*.lock",
    "*.zip",
    "*.css",
    "*.json",
    "*.zsh",
    "*/packages.nix",
    "*/home/default.nix",
    "treefmt.toml",
]

[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]
excludes = [ ]

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]

[formatter.statix]
command = "statix"
options = ["fix"]
includes = ["*.nix"]

[formatter.sh]
command = "shfmt"
options = [ "-l", "-w", "-ci", "-sr", "-i", "4" ]
includes = [ "*.sh" ]
excludes = []